print("Demarrage 'loopTEST.py'")
hint("loopTEST",1)
sleep(3)
while True: #Seconde boucle infinie permettant d'utiliser la commande "break" pour arreter la transaction
    RFID_waitRetireCarte() #Attente d'absence de cartes
    hint("plus de carte",4)
    sleep(1)
    hint("",4)
    MENU_menuPrincipal() #Attente d'une carte et possibilité de naviguer dans les menus
    print("###############")
    print("debut lecture")
    UID,argent,codeCarte,hashUID,hashArgent=RFID_readCarte() #Multi lecture des données de la carte
    print("uid        :"+UID)
    print("argent     :"+str(argent))
    print("HashGuinche:"+codeCarte)
    print("hashUID    :"+hashUID)
    print("hashArgent :"+hashArgent)
    print("###############")
    print("debut ecriture")
    RFID_setArgent(6475,UID)
    RFID_setHashCodeType(config.codeGuinche,UID)
    RFID_setHashUID(UID)
    print("###############")
    print("relecture")
    UID,argent,codeCarte,hashUID,hashArgent=RFID_readCarte() #Multi lecture des données de la carte
    print("uid        :"+UID)
    print("uidInt     :"+str(STRING_uidStrToInt(UID)))
    print("argent     :"+str(argent))
    print("HashGuinche:"+codeCarte)
    print("hashUID    :"+hashUID)
    print("hashArgent :"+hashArgent)
    print("###############")
    print()
